# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gateway_egress_pb2 as gateway__egress__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_egress_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayEgressStub:
    """上流（Building OS）に配置される gRPC IF。ゲートウェイ（建物エッジ）は
    クラスタ外クライアントとして 1 本の双方向 stream を張る。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/bbc_sim.gateway_egress.v1.GatewayEgress/Connect',
                request_serializer=gateway__egress__pb2.ClientMessage.SerializeToString,
                response_deserializer=gateway__egress__pb2.ServerMessage.FromString,
                _registered_method=True)


class GatewayEgressServicer:
    """上流（Building OS）に配置される gRPC IF。ゲートウェイ（建物エッジ）は
    クラスタ外クライアントとして 1 本の双方向 stream を張る。
    """

    def Connect(self, request_iterator, context):
        """ゲートウェイごと 1 本の双方向 stream。クライアントは ClientMessage(Hello) で開始し、
        以後サーバが ControlCommand を push、クライアントが ControlResult を返す。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayEgressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=gateway__egress__pb2.ClientMessage.FromString,
                    response_serializer=gateway__egress__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bbc_sim.gateway_egress.v1.GatewayEgress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bbc_sim.gateway_egress.v1.GatewayEgress', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayEgress:
    """上流（Building OS）に配置される gRPC IF。ゲートウェイ（建物エッジ）は
    クラスタ外クライアントとして 1 本の双方向 stream を張る。
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bbc_sim.gateway_egress.v1.GatewayEgress/Connect',
            gateway__egress__pb2.ClientMessage.SerializeToString,
            gateway__egress__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
