# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_egress.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gateway_egress.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gateway_egress.proto\x12\x19\x62\x62\x63_sim.gateway_egress.v1\"\x89\x01\n\rClientMessage\x12\x31\n\x05hello\x18\x01 \x01(\x0b\x32 .bbc_sim.gateway_egress.v1.HelloH\x00\x12:\n\x06result\x18\x02 \x01(\x0b\x32(.bbc_sim.gateway_egress.v1.ControlResultH\x00\x42\t\n\x07payload\"X\n\rServerMessage\x12<\n\x07\x63ommand\x18\x01 \x01(\x0b\x32).bbc_sim.gateway_egress.v1.ControlCommandH\x00\x42\t\n\x07payload\"\x1b\n\x05Hello\x12\x12\n\ngateway_id\x18\x01 \x01(\t\"q\n\x0e\x43ontrolCommand\x12\x12\n\ncontrol_id\x18\x01 \x01(\t\x12\x10\n\x08point_id\x18\x02 \x01(\t\x12\x15\n\rpresent_value\x18\x06 \x01(\x01\x12\x10\n\x08priority\x18\x07 \x01(\rJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06\"F\n\rControlResult\x12\x12\n\ncontrol_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x10\n\x08response\x18\x03 \x01(\t2r\n\rGatewayEgress\x12\x61\n\x07\x43onnect\x12(.bbc_sim.gateway_egress.v1.ClientMessage\x1a(.bbc_sim.gateway_egress.v1.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_egress_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=52
  _globals['_CLIENTMESSAGE']._serialized_end=189
  _globals['_SERVERMESSAGE']._serialized_start=191
  _globals['_SERVERMESSAGE']._serialized_end=279
  _globals['_HELLO']._serialized_start=281
  _globals['_HELLO']._serialized_end=308
  _globals['_CONTROLCOMMAND']._serialized_start=310
  _globals['_CONTROLCOMMAND']._serialized_end=423
  _globals['_CONTROLRESULT']._serialized_start=425
  _globals['_CONTROLRESULT']._serialized_end=495
  _globals['_GATEWAYEGRESS']._serialized_start=497
  _globals['_GATEWAYEGRESS']._serialized_end=611
# @@protoc_insertion_point(module_scope)
