# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gateway_ingress_pb2 as gateway__ingress__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_ingress_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayIngressStub:
    """GW 側からクラスタ内 Building OS へ上りテレメトリを stream する。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/gatewaybridge.GatewayIngress/StreamTelemetry',
                request_serializer=gateway__ingress__pb2.TelemetryFrame.SerializeToString,
                response_deserializer=gateway__ingress__pb2.StreamAck.FromString,
                _registered_method=True)


class GatewayIngressServicer:
    """GW 側からクラスタ内 Building OS へ上りテレメトリを stream する。
    """

    def StreamTelemetry(self, request_iterator, context):
        """GW が TelemetryFrame を client-streaming で送り、サーバが StreamAck を返す。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayIngressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=gateway__ingress__pb2.TelemetryFrame.FromString,
                    response_serializer=gateway__ingress__pb2.StreamAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gatewaybridge.GatewayIngress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gatewaybridge.GatewayIngress', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayIngress:
    """GW 側からクラスタ内 Building OS へ上りテレメトリを stream する。
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gatewaybridge.GatewayIngress/StreamTelemetry',
            gateway__ingress__pb2.TelemetryFrame.SerializeToString,
            gateway__ingress__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
