# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway_ingress.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gateway_ingress.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gateway_ingress.proto\x12\rgatewaybridge\"\xce\x01\n\x0eTelemetryFrame\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x10\n\x08point_id\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x41\n\nattributes\x18\x05 \x03(\x0b\x32-.gatewaybridge.TelemetryFrame.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\tStreamAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x03\x32^\n\x0eGatewayIngress\x12L\n\x0fStreamTelemetry\x12\x1d.gatewaybridge.TelemetryFrame\x1a\x18.gatewaybridge.StreamAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_ingress_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYFRAME_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_TELEMETRYFRAME_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYFRAME']._serialized_start=41
  _globals['_TELEMETRYFRAME']._serialized_end=247
  _globals['_TELEMETRYFRAME_ATTRIBUTESENTRY']._serialized_start=198
  _globals['_TELEMETRYFRAME_ATTRIBUTESENTRY']._serialized_end=247
  _globals['_STREAMACK']._serialized_start=249
  _globals['_STREAMACK']._serialized_end=278
  _globals['_GATEWAYINGRESS']._serialized_start=280
  _globals['_GATEWAYINGRESS']._serialized_end=374
# @@protoc_insertion_point(module_scope)
